In [32]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/psabhay2003/BCGX-GenAI/refs/heads/main/10K.csv')
df

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Operating Cash Flow,Financing Cash Flow,Investing Cash Flow,Gross Margin
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000,37757000000,96970000000,171008000000
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000,43935000000,22680000000,146052000000
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000,58876000000,30311000000,135650000000
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000,3853000000,18787000000,17450000000
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000,2589000000,15584000000,17660000000
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000,3527000000,11973000000,20853000000
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000,121983000000,2935000000,180683000000
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000,108488000000,3705000000,169148000000
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000,110749000000,22354000000,170782000000

In [33]:
# Convert all numerical columns to standard number format (removing scientific notation)
pd.options.display.float_format = '{:.0f}'.format
df

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Operating Cash Flow,Financing Cash Flow,Investing Cash Flow,Gross Margin
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000,37757000000,96970000000,171008000000
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000,43935000000,22680000000,146052000000
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000,58876000000,30311000000,135650000000
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000,3853000000,18787000000,17450000000
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000,2589000000,15584000000,17660000000
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000,3527000000,11973000000,20853000000
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000,121983000000,2935000000,180683000000
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000,108488000000,3705000000,169148000000
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000,110749000000,22354000000,170782000000

In [34]:
df.describe()

,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Operating Cash Flow,Financing Cash Flow,Investing Cash Flow,Gross Margin
count,9,9,9,9,9,9,9,9,9
mean,2023,233320000000,62048666667,296702555556,186236222222,76557333333,54639666667,25033222222,114365111111
std,1,130006968331,39094383970,153240424606,114506220759,48272769855,48607674011,28411194553,73089454727
min,2022,81462000000,7153000000,82338000000,36440000000,13256000000,2589000000,2935000000,17450000000
25%,2022,97690000000,14974000000,122070000000,48390000000,14923000000,3853000000,11973000000,20853000000
50%,2023,211915000000,72738000000,352755000000,205753000000,89035000000,43935000000,18787000000,146052000000
75%,2024,383285000000,93736000000,364980000000,290437000000,118254000000,108488000000,22680000000,170782000000
max,2024,394328000000,99803000000,512163000000,308030000000,122151000000,121983000000,96970000000,180683000000

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Company              9 non-null      object
 1   Year                 9 non-null      int64
 2   Total Revenue        9 non-null      float64
 3   Net Income           9 non-null      int64
 4   Total Assets         9 non-null      float64
 5   Total Liabilities    9 non-null      float64
 6   Operating Cash Flow  9 non-null      float64
 7   Financing Cash Flow  9 non-null      float64
 8   Investing Cash Flow  9 non-null      int64
 9   Gross Margin         9 non-null      float64
dtypes: float64(6), int64(3), object(1)
memory usage: 852.0+ bytes

In [36]:
df = df.sort_values(['Company','Year'],ascending=True).groupby('Company').head()
df

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Operating Cash Flow,Financing Cash Flow,Investing Cash Flow,Gross Margin
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000,110749000000,22354000000,170782000000
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000,108488000000,3705000000,169148000000
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000,121983000000,2935000000,180683000000
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000,58876000000,30311000000,135650000000
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000,43935000000,22680000000,146052000000
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000,37757000000,96970000000,171008000000
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000,3527000000,11973000000,20853000000
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000,2589000000,15584000000,17660000000
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000,3853000000,18787000000,17450000000

In [37]:
revenue = pd.DataFrame(columns=['Company','Year', 'Total Revenue'])
revenue['Company'] = df['Company']
revenue['Year'] = df['Year']
revenue['Total Revenue'] = df['Total Revenue']
revenue['Revenue Growth (%)'] = df.groupby(['Company'])['Total Revenue'].pct_change() * 100
revenue
Revenue_Growth = revenue['Revenue Growth (%)']
df = pd.concat([df, Revenue_Growth], axis=1)
df
#Microsoft and Tesla reported a net positive revenue growth whereas Apple reported a dip of 1% in revenue in the three fiscal years.
#Microsoft reported more than double revenue growth from 2023-24 whereas Tesla reported a massive revenue growth of 19% in 2023.

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Operating Cash Flow,Financing Cash Flow,Investing Cash Flow,Gross Margin,Revenue Growth (%)
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000,110749000000,22354000000,170782000000,NaN
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000,108488000000,3705000000,169148000000,-3
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000,121983000000,2935000000,180683000000,2
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000,58876000000,30311000000,135650000000,NaN
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000,43935000000,22680000000,146052000000,7
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000,37757000000,96970000000,171008000000,16
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000,3527000000,11973000000,20853000000,NaN
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000,2589000000,15584000000,17660000000,19
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000,3853000000,18787000000,17450000000,1

In [38]:
income = pd.DataFrame(columns=['Company','Year','Net Income','Net Income Growth (%)'])
income['Company'] = df['Company']
income['Year'] = df['Year']
income['Net Income'] = df['Net Income']
income['Net Income Growth (%)'] = df.groupby(['Company'])['Net Income'].pct_change() * 100
income
Net_Income_Growth = income['Net Income Growth (%)']
df = pd.concat([df, Net_Income_Growth], axis=1)
df
#Apple reported a net decrease of 6% in net income from 2022-24, Microsoft reported a net increase of 21% in net income from 2022-24 showing significant improvement.
#Tesla reported a massive dip of a net 33% decrease in income from 2022-24.

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Operating Cash Flow,Financing Cash Flow,Investing Cash Flow,Gross Margin,Revenue Growth (%),Net Income Growth (%)
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000,110749000000,22354000000,170782000000,NaN,NaN
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000,108488000000,3705000000,169148000000,-3,-3
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000,121983000000,2935000000,180683000000,2,-3
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000,58876000000,30311000000,135650000000,NaN,NaN
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000,43935000000,22680000000,146052000000,7,-1
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000,37757000000,96970000000,171008000000,16,22
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000,3527000000,11973000000,20853000000,NaN,NaN
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000,2589000000,15584000000,17660000000,19,19
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000,3853000000,18787000000,17450000000,1,-52

In [39]:
assets = pd.DataFrame(columns=['Company','Year','Total Assets','Total Assets Growth (%)'])
assets['Company'] = df['Company']
assets['Year'] = df['Year']
assets['Total Assets'] = df['Total Assets']
assets['Total Assets Growth (%)'] = df.groupby(['Company'])['Total Assets'].pct_change() * 100
assets
Total_Assets_Growth = assets['Total Assets Growth (%)']
df = pd.concat([df, Total_Assets_Growth], axis=1)
df
#Apple, Microsoft, and Tesla reported a net increase of 4%, 37%, 43% respectively in Total Assets Growth from 2022-2024.

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Operating Cash Flow,Financing Cash Flow,Investing Cash Flow,Gross Margin,Revenue Growth (%),Net Income Growth (%),Total Assets Growth (%)
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000,110749000000,22354000000,170782000000,NaN,NaN,NaN
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000,108488000000,3705000000,169148000000,-3,-3,-0
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000,121983000000,2935000000,180683000000,2,-3,4
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000,58876000000,30311000000,135650000000,NaN,NaN,NaN
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000,43935000000,22680000000,146052000000,7,-1,13
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000,37757000000,96970000000,171008000000,16,22,24
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000,3527000000,11973000000,20853000000,NaN,NaN,NaN
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000,2589000000,15584000000,17660000000,19,19,29
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000,3853000000,18787000000,17450000000,1,-52,14

In [40]:
liability = pd.DataFrame(columns=['Company','Year','Total Liabilities','Total Liabilities Growth (%)'])
liability['Company'] = df['Company']
liability['Year'] = df['Year']
liability['Total Liabilities'] = df['Total Liabilities']
liability['Total Liabilities Growth (%)'] = df.groupby(['Company'])['Total Liabilities'].pct_change() * 100
liability
Total_Assets_Growth = liability['Total Liabilities Growth (%)']
df = pd.concat([df, Total_Assets_Growth], axis=1)
df
#The total Liabilities Growth showed an increasing trend for all three companies from 2022 to 2024.
#The growth percentage reports a massive increase of 18% in Total Liabilities of Microsoft for the fiscal year 2024, whereas a decrease from 18% to 13% for Tesla for the same fiscal year.

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Operating Cash Flow,Financing Cash Flow,Investing Cash Flow,Gross Margin,Revenue Growth (%),Net Income Growth (%),Total Assets Growth (%),Total Liabilities Growth (%)
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000,110749000000,22354000000,170782000000,NaN,NaN,NaN,NaN
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000,108488000000,3705000000,169148000000,-3,-3,-0,-4
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000,121983000000,2935000000,180683000000,2,-3,4,6
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000,58876000000,30311000000,135650000000,NaN,NaN,NaN,NaN
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000,43935000000,22680000000,146052000000,7,-1,13,4
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000,37757000000,96970000000,171008000000,16,22,24,18
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000,3527000000,11973000000,20853000000,NaN,NaN,NaN,NaN
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000,2589000000,15584000000,17660000000,19,19,29,18
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000,3853000000,18787000000,17450000000,1,-52,14,13

In [41]:
cashflow = pd.DataFrame(columns=['Company','Year','Operating Cash Flow','Cash Flow Growth (%)'])
cashflow['Company'] = df['Company']
cashflow['Year'] = df['Year']
cashflow['Operating Cash Flow'] = df['Operating Cash Flow']
cashflow['Operating Cash Flow Growth (%)'] = df.groupby(['Company'])['Operating Cash Flow'].pct_change() * 100
cashflow
Operating_Cash_Flow_Growth = cashflow['Operating Cash Flow Growth (%)']
df = pd.concat([df, Operating_Cash_Flow_Growth], axis=1)
df
#The operating cashflow rate shows a decreasing trend for all three companies during the fiscal year 2022-23, with Microsoft reporting the least decrease of 2%.
#Although it also shows an increasing trend for all three companies during the fiscal year 2023-24, with Microsoft reporting the highest increase of 35%.

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Operating Cash Flow,Financing Cash Flow,Investing Cash Flow,Gross Margin,Revenue Growth (%),Net Income Growth (%),Total Assets Growth (%),Total Liabilities Growth (%),Operating Cash Flow Growth (%)
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000,110749000000,22354000000,170782000000,NaN,NaN,NaN,NaN,NaN
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000,108488000000,3705000000,169148000000,-3,-3,-0,-4,-10
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000,121983000000,2935000000,180683000000,2,-3,4,6,7
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000,58876000000,30311000000,135650000000,NaN,NaN,NaN,NaN,NaN
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000,43935000000,22680000000,146052000000,7,-1,13,4,-2
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000,37757000000,96970000000,171008000000,16,22,24,18,35
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000,3527000000,11973000000,20853000000,NaN,NaN,NaN,NaN,NaN
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000,2589000000,15584000000,17660000000,19,19,29,18,-10
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000,3853000000,18787000000,17450000000,1,-52,14,13,13

In [42]:
cashflow = pd.DataFrame(columns=['Company','Year','Financing Cash Flow','Cash Flow Growth (%)'])
cashflow['Company'] = df['Company']
cashflow['Year'] = df['Year']
cashflow['Financing Cash Flow'] = df['Financing Cash Flow']
cashflow['Financing Cash Flow Growth (%)'] = df.groupby(['Company'])['Financing Cash Flow'].pct_change() * 100
cashflow
Financing_Cash_Flow_Growth = cashflow['Financing Cash Flow Growth (%)']
df = pd.concat([df, Financing_Cash_Flow_Growth], axis=1)
df
#The financing cashflow rate shows a decreasing trend for all three companies during the fiscal year 2022-23, with Apple reporting the least decrease of 2%.
#Although it also shows an increasing trend for all three companies during the fiscal year 2023-24, with Tesla reporting the highest increase of 49%.

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Operating Cash Flow,Financing Cash Flow,Investing Cash Flow,Gross Margin,Revenue Growth (%),Net Income Growth (%),Total Assets Growth (%),Total Liabilities Growth (%),Operating Cash Flow Growth (%),Financing Cash Flow Growth (%)
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000,110749000000,22354000000,170782000000,NaN,NaN,NaN,NaN,NaN,NaN
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000,108488000000,3705000000,169148000000,-3,-3,-0,-4,-10,-2
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000,121983000000,2935000000,180683000000,2,-3,4,6,7,12
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000,58876000000,30311000000,135650000000,NaN,NaN,NaN,NaN,NaN,NaN
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000,43935000000,22680000000,146052000000,7,-1,13,4,-2,-25
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000,37757000000,96970000000,171008000000,16,22,24,18,35,-14
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000,3527000000,11973000000,20853000000,NaN,NaN,NaN,NaN,NaN,NaN
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000,2589000000,15584000000,17660000000,19,19,29,18,-10,-27
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000,3853000000,18787000000,17450000000,1,-52,14,13,13,49

In [43]:
cashflow = pd.DataFrame(columns=['Company','Year','Investing Cash Flow','Cash Flow Growth (%)'])
cashflow['Company'] = df['Company']
cashflow['Year'] = df['Year']
cashflow['Investing Cash Flow'] = df['Investing Cash Flow']
cashflow['Investing Cash Flow Growth (%)'] = df.groupby(['Company'])['Investing Cash Flow'].pct_change() * 100
cashflow
Investing_Cash_Flow_Growth = cashflow['Investing Cash Flow Growth (%)']
df = pd.concat([df, Investing_Cash_Flow_Growth], axis=1)
df
#The investing cashflow rate show very skewed trend for all three companies.

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Operating Cash Flow,Financing Cash Flow,Investing Cash Flow,Gross Margin,Revenue Growth (%),Net Income Growth (%),Total Assets Growth (%),Total Liabilities Growth (%),Operating Cash Flow Growth (%),Financing Cash Flow Growth (%),Investing Cash Flow Growth (%)
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000,110749000000,22354000000,170782000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000,108488000000,3705000000,169148000000,-3,-3,-0,-4,-10,-2,-83
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000,121983000000,2935000000,180683000000,2,-3,4,6,7,12,-21
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000,58876000000,30311000000,135650000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000,43935000000,22680000000,146052000000,7,-1,13,4,-2,-25,-25
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000,37757000000,96970000000,171008000000,16,22,24,18,35,-14,328
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000,3527000000,11973000000,20853000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000,2589000000,15584000000,17660000000,19,19,29,18,-10,-27,30
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000,3853000000,18787000000,17450000000,1,-52,14,13,13,49,21

In [44]:
gross_margin = pd.DataFrame(columns=['Company','Year','Gross Margin','Gross Margin Growth (%)'])
gross_margin['Company'] = df['Company']
gross_margin['Year'] = df['Year']
gross_margin['Gross Margin'] = df['Gross Margin']
gross_margin['Gross Margin Growth (%)'] = df.groupby(['Company'])['Gross Margin'].pct_change() * 100
gross_margin
Gross_Margin_Growth = gross_margin['Gross Margin Growth (%)']
df = pd.concat([df, Gross_Margin_Growth], axis=1)
df
#The gross margin growth reported a decreasing trend for Apple and Tesla but an increasing trend for Microsoft in the fiscal year 2022-23.
#The gross margin growth reported an increasing trend for all three companies with Microsoft reporting the highest increase of 17% during the fiscal year 2023-24.

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Operating Cash Flow,Financing Cash Flow,Investing Cash Flow,Gross Margin,Revenue Growth (%),Net Income Growth (%),Total Assets Growth (%),Total Liabilities Growth (%),Operating Cash Flow Growth (%),Financing Cash Flow Growth (%),Investing Cash Flow Growth (%),Gross Margin Growth (%)
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000,110749000000,22354000000,170782000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000,108488000000,3705000000,169148000000,-3,-3,-0,-4,-10,-2,-83,-1
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000,121983000000,2935000000,180683000000,2,-3,4,6,7,12,-21,7
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000,58876000000,30311000000,135650000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000,43935000000,22680000000,146052000000,7,-1,13,4,-2,-25,-25,8
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000,37757000000,96970000000,171008000000,16,22,24,18,35,-14,328,17
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000,3527000000,11973000000,20853000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000,2589000000,15584000000,17660000000,19,19,29,18,-10,-27,30,-15
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000,3853000000,18787000000,17450000000,1,-52,14,13,13,49,21,-1

In [45]:
#Adding a new feature 'Profit Margin'
def calculate_profit_margin(row):
  net_income = row['Net Income']
  total_revenue = row['Total Revenue']
  Profit_Margin = (net_income / total_revenue) * 100
  return Profit_Margin
df['Profit_Margin'] = df.apply(calculate_profit_margin, axis=1)
df

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Operating Cash Flow,Financing Cash Flow,Investing Cash Flow,Gross Margin,Revenue Growth (%),Net Income Growth (%),Total Assets Growth (%),Total Liabilities Growth (%),Operating Cash Flow Growth (%),Financing Cash Flow Growth (%),Investing Cash Flow Growth (%),Gross Margin Growth (%),Profit_Margin
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000,110749000000,22354000000,170782000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000,108488000000,3705000000,169148000000,-3,-3,-0,-4,-10,-2,-83,-1,25
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000,121983000000,2935000000,180683000000,2,-3,4,6,7,12,-21,7,24
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000,58876000000,30311000000,135650000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000,43935000000,22680000000,146052000000,7,-1,13,4,-2,-25,-25,8,34
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000,37757000000,96970000000,171008000000,16,22,24,18,35,-14,328,17,36
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000,3527000000,11973000000,20853000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000,2589000000,15584000000,17660000000,19,19,29,18,-10,-27,30,-15,15
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000,3853000000,18787000000,17450000000,1,-52,14,13,13,49,21,-1,7

In [46]:
#Adding a new feature 'Return on Assets(ROA)'
def calculate_roa(row):
  net_income = row['Net Income']
  total_assets = row['Total Assets']
  ROA = (net_income / total_assets) * 100
  return ROA
df['ROA'] = df.apply(calculate_roa, axis=1)
df

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Operating Cash Flow,Financing Cash Flow,Investing Cash Flow,Gross Margin,Revenue Growth (%),Net Income Growth (%),Total Assets Growth (%),Total Liabilities Growth (%),Operating Cash Flow Growth (%),Financing Cash Flow Growth (%),Investing Cash Flow Growth (%),Gross Margin Growth (%),Profit_Margin,ROA
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000,110749000000,22354000000,170782000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25,28
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000,108488000000,3705000000,169148000000,-3,-3,-0,-4,-10,-2,-83,-1,25,28
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000,121983000000,2935000000,180683000000,2,-3,4,6,7,12,-21,7,24,26
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000,58876000000,30311000000,135650000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,20
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000,43935000000,22680000000,146052000000,7,-1,13,4,-2,-25,-25,8,34,18
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000,37757000000,96970000000,171008000000,16,22,24,18,35,-14,328,17,36,17
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000,3527000000,11973000000,20853000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000,2589000000,15584000000,17660000000,19,19,29,18,-10,-27,30,-15,15,14
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000,3853000000,18787000000,17450000000,1,-52,14,13,13,49,21,-1,7,6

In [47]:
#Adding a new feature 'Return on Equity(ROE)'
def calculate_roe(row):
  net_income = row['Net Income']
  equity = row['Total Assets'] - row['Total Liabilities']
  ROE = (net_income / equity) * 100
  return ROE
df['ROE'] = df.apply(calculate_roe, axis=1)
df

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Operating Cash Flow,Financing Cash Flow,Investing Cash Flow,Gross Margin,...,Net Income Growth (%),Total Assets Growth (%),Total Liabilities Growth (%),Operating Cash Flow Growth (%),Financing Cash Flow Growth (%),Investing Cash Flow Growth (%),Gross Margin Growth (%),Profit_Margin,ROA,ROE
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000,110749000000,22354000000,170782000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25,28,197
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000,108488000000,3705000000,169148000000,...,-3,-0,-4,-10,-2,-83,-1,25,28,156
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000,121983000000,2935000000,180683000000,...,-3,4,6,7,12,-21,7,24,26,165
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000,58876000000,30311000000,135650000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,20,44
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000,43935000000,22680000000,146052000000,...,-1,13,4,-2,-25,-25,8,34,18,35
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000,37757000000,96970000000,171008000000,...,22,24,18,35,-14,328,17,36,17,33
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000,3527000000,11973000000,20853000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15,27
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000,2589000000,15584000000,17660000000,...,19,29,18,-10,-27,30,-15,15,14,24
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000,3853000000,18787000000,17450000000,...,-52,14,13,13,49,21,-1,7,6,10

In [48]:
# Generate Question-Answer Pairs
qa_pairs = []
for index, row in df.iterrows():
    qa_pairs.append((f"What is {row['Company']}'s revenue in {row['Year']}?", f"{row['Total Revenue']}"))
    qa_pairs.append((f"What is {row['Company']}'s net income in {row['Year']}?", f"{row['Net Income']}"))
    qa_pairs.append((f"What are {row['Company']}'s total assets in {row['Year']}?", f"{row['Total Assets']}"))
    qa_pairs.append((f"What are {row['Company']}'s total liabilities in {row['Year']}?", f"{row['Total Liabilities']}"))
    qa_pairs.append((f"What is {row['Company']}'s operating cashflow in {row['Year']}?", f"{row['Operating Cash Flow']}"))
    qa_pairs.append((f"What is {row['Company']}'s financing cashflow in {row['Year']}?", f"{row['Financing Cash Flow']}"))
    qa_pairs.append((f"What is {row['Company']}'s investing cashflow in {row['Year']}?", f"{row['Investing Cash Flow']}"))
    qa_pairs.append((f"What is {row['Company']}'s gross margin in {row['Year']}?", f"{row['Gross Margin']}"))
    qa_pairs.append((f"What is {row['Company']}'s revenue growth in {row['Year']}?", f"{row['Revenue Growth (%)']}"))
    qa_pairs.append((f"What is {row['Company']}'s net income growth in {row['Year']}?", f"{row['Net Income Growth (%)']}"))
    qa_pairs.append((f"What is {row['Company']}'s total assets growth in {row['Year']}?", f"{row['Total Assets Growth (%)']}"))
    qa_pairs.append((f"What is {row['Company']}'s total liabilities growth in {row['Year']}?", f"{row['Total Liabilities Growth (%)']}"))
    qa_pairs.append((f"What is {row['Company']}'s operating cashflow growth in {row['Year']}?", f"{row['Operating Cash Flow Growth (%)']}"))
    qa_pairs.append((f"What is {row['Company']}'s financing cashflow growth in {row['Year']}?", f"{row['Financing Cash Flow Growth (%)']}"))
    qa_pairs.append((f"What is {row['Company']}'s investing cashflow growth in {row['Year']}?", f"{row['Investing Cash Flow Growth (%)']}"))
    qa_pairs.append((f"What is {row['Company']}'s gross margin growth in {row['Year']}?", f"{row['Gross Margin Growth (%)']}"))
    qa_pairs.append((f"What is {row['Company']}'s profit margin in {row['Year']}?", f"{row['Profit_Margin']}"))
    qa_pairs.append((f"What is {row['Company']}'s return on assets in {row['Year']}?", f"{row['ROA']}"))
    qa_pairs.append((f"What is {row['Company']}'s return on equity in {row['Year']}?", f"{row['ROE']}"))

# Convert to DataFrame
qa_df = pd.DataFrame(qa_pairs, columns=["question", "response"])
qa_df.to_csv("financial_chatbot_data.csv", index=False)
qa_df

                                              question             response
0                     What is Apple's revenue in 2022?       394328000000.0
1                  What is Apple's net income in 2022?          99803000000
2               What are Apple's total assets in 2022?       352755000000.0
3          What are Apple's total liabilities in 2022?       302083000000.0
4          What is Apple's operating cashflow in 2022?       122151000000.0
..                                                 ...                  ...
166  What is Tesla's investing cashflow growth in 2...    20.55313141683779
167       What is Tesla's gross margin growth in 2024?  -1.1891279728199367
168             What is Tesla's profit margin in 2024?    7.322141467908691
169          What is Tesla's return on assets in 2024?    5.859752600966658
170          What is Tesla's return on equity in 2024?    9.708197611292075

[171 rows x 2 columns]

In [49]:
qa_df.replace("nan", np.nan, inplace=True)
qa_df = qa_df.dropna()
qa_df

                                              question             response
0                     What is Apple's revenue in 2022?       394328000000.0
1                  What is Apple's net income in 2022?          99803000000
2               What are Apple's total assets in 2022?       352755000000.0
3          What are Apple's total liabilities in 2022?       302083000000.0
4          What is Apple's operating cashflow in 2022?       122151000000.0
..                                                 ...                  ...
166  What is Tesla's investing cashflow growth in 2...    20.55313141683779
167       What is Tesla's gross margin growth in 2024?  -1.1891279728199367
168             What is Tesla's profit margin in 2024?    7.322141467908691
169          What is Tesla's return on assets in 2024?    5.859752600966658
170          What is Tesla's return on equity in 2024?    9.708197611292075

[147 rows x 2 columns]

In [50]:
'''import os
os.makedirs('/mnt/data', exist_ok=True)
qa_df.to_csv('/mnt/data/financial_chatbot_data.csv', index=False)
from google.colab import files
files.download("/mnt/data/financial_chatbot_data.csv")'''

'import os\nos.makedirs(\'/mnt/data\', exist_ok=True)\nqa_df.to_csv(\'/mnt/data/financial_chatbot_data.csv\', index=False)\nfrom google.colab import files\nfiles.download("/mnt/data/financial_chatbot_data.csv")'