In [1]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/psabhay2003/BCGX-GenAI/refs/heads/main/10K.csv')
df

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow
0,Microsoft,2024,2.451220e+11,8.813600e+10,5.121630e+11,2.436860e+11,1.185480e+11
1,Microsoft,2023,2.119150e+11,7.231600e+10,4.119760e+11,2.057530e+11,8.758200e+10
2,Microsoft,2022,1.982700e+11,7.273800e+10,3.648400e+11,1.982980e+11,8.903500e+10
3,Tesla,2024,9.769000e+10,7.153000e+09,1.220700e+11,4.839000e+10,1.492300e+10
4,Tesla,2023,9.677300e+10,1.497400e+10,1.066180e+11,4.300900e+10,1.325600e+10
5,Tesla,2022,8.146200e+10,1.258700e+10,8.233800e+10,3.644000e+10,1.472400e+10
6,Apple,2024,3.910350e+11,9.373600e+10,3.649800e+11,3.080300e+11,1.182540e+11
7,Apple,2023,3.832850e+11,9.699500e+10,3.525830e+11,2.904370e+11,1.105430e+11
8,Apple,2022,3.943280e+11,9.980300e+10,3.527550e+11,3.020830e+11,1.221510e+11

In [2]:
# Convert all numerical columns to standard number format (removing scientific notation)
pd.options.display.float_format = '{:.0f}'.format
df

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000

In [3]:
df.describe()

,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow
count,9,9,9,9,9,9
mean,2023,233320000000,62048666667,296702555556,186236222222,76557333333
std,1,130006968331,39094383970,153240424606,114506220759,48272769855
min,2022,81462000000,7153000000,82338000000,36440000000,13256000000
25%,2022,97690000000,14974000000,122070000000,48390000000,14923000000
50%,2023,211915000000,72738000000,352755000000,205753000000,89035000000
75%,2024,383285000000,93736000000,364980000000,290437000000,118254000000
max,2024,394328000000,99803000000,512163000000,308030000000,122151000000

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 8 to 3
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Company            9 non-null      object
 1   Year               9 non-null      int64
 2   Total Revenue      9 non-null      float64
 3   Net Income         9 non-null      float64
 4   Total Assets       9 non-null      float64
 5   Total Liabilities  9 non-null      float64
 6   Cash Flow          9 non-null      float64
dtypes: float64(5), int64(1), object(1)
memory usage: 576.0+ bytes

In [5]:
df = df.sort_values(['Company','Year'],ascending=True).groupby('Company').head()
df

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000

In [15]:
revenue = pd.DataFrame(columns=['Company','Year', 'Total Revenue'])
revenue['Company'] = df['Company']
revenue['Year'] = df['Year']
revenue['Total Revenue'] = df['Total Revenue']
revenue['Revenue Growth (%)'] = df.groupby(['Company'])['Total Revenue'].pct_change() * 100
revenue
Revenue_Growth = revenue['Revenue Growth (%)']
df = pd.concat([df, Revenue_Growth], axis=1)
df
#Microsoft and Tesla reported a net positive revenue growth whereas Apple reported a dip of 1% in revenue in the three fiscal years.
#Microsoft reported more than double revenue growth from 2023-24 whereas Tesla reported a massive revenue growth of 19% in 2023.

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow,Revenue Growth (%)
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000,NaN
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000,-3
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000,2
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000,NaN
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000,7
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000,16
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000,NaN
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000,19
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000,1

In [16]:
income = pd.DataFrame(columns=['Company','Year','Net Income','Net Income Growth (%)'])
income['Company'] = df['Company']
income['Year'] = df['Year']
income['Net Income'] = df['Net Income']
income['Net Income Growth (%)'] = df.groupby(['Company'])['Net Income'].pct_change() * 100
income
Net_Income_Growth = income['Net Income Growth (%)']
df = pd.concat([df, Net_Income_Growth], axis=1)
df
#Apple reported a net decrease of 6% in net income from 2022-24, Microsoft reported a net increase of 21% in net income from 2022-24 showing significant improvement.
#Tesla reported a massive dip of a net 33% decrease in income from 2022-24.

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow,Revenue Growth (%),Net Income Growth (%)
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000,NaN,NaN
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000,-3,-3
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000,2,-3
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000,NaN,NaN
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000,7,-1
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000,16,22
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000,NaN,NaN
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000,19,19
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000,1,-52

In [17]:
assets = pd.DataFrame(columns=['Company','Year','Total Assets','Total Assets Growth (%)'])
assets['Company'] = df['Company']
assets['Year'] = df['Year']
assets['Total Assets'] = df['Total Assets']
assets['Total Assets Growth (%)'] = df.groupby(['Company'])['Total Assets'].pct_change() * 100
assets
Total_Assets_Growth = assets['Total Assets Growth (%)']
df = pd.concat([df, Total_Assets_Growth], axis=1)
df
#Apple, Microsoft, and Tesla reported a net increase of 4%, 37%, 43% respectively in Total Assets Growth from 2022-2024.

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow,Revenue Growth (%),Net Income Growth (%),Total Assets Growth (%)
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000,NaN,NaN,NaN
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000,-3,-3,-0
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000,2,-3,4
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000,NaN,NaN,NaN
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000,7,-1,13
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000,16,22,24
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000,NaN,NaN,NaN
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000,19,19,29
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000,1,-52,14

In [18]:
liability = pd.DataFrame(columns=['Company','Year','Total Liabilities','Total Liabilities Growth (%)'])
liability['Company'] = df['Company']
liability['Year'] = df['Year']
liability['Total Liabilities'] = df['Total Liabilities']
liability['Total Liabilities Growth (%)'] = df.groupby(['Company'])['Total Liabilities'].pct_change() * 100
liability
Total_Assets_Growth = liability['Total Liabilities Growth (%)']
df = pd.concat([df, Total_Assets_Growth], axis=1)
df
#The total Liabilities Growth showed an increasing trend for all three companies from 2022 to 2024.
#The growth percentage reports a massive increase of 18% in Total Liabilities of Microsoft for the fiscal year 2024, whereas a decrease from 18% to 13% for Tesla for the same fiscal year.

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow,Revenue Growth (%),Net Income Growth (%),Total Assets Growth (%),Total Liabilities Growth (%)
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000,NaN,NaN,NaN,NaN
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000,-3,-3,-0,-4
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000,2,-3,4,6
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000,NaN,NaN,NaN,NaN
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000,7,-1,13,4
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000,16,22,24,18
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000,NaN,NaN,NaN,NaN
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000,19,19,29,18
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000,1,-52,14,13

In [19]:
cashflow = pd.DataFrame(columns=['Company','Year','Cash Flow','Cash Flow Growth (%)'])
cashflow['Company'] = df['Company']
cashflow['Year'] = df['Year']
cashflow['Cash Flow'] = df['Cash Flow']
cashflow['Cash Flow Growth (%)'] = df.groupby(['Company'])['Cash Flow'].pct_change() * 100
cashflow
Cash_Flow_Growth = cashflow['Cash Flow Growth (%)']
df = pd.concat([df, Cash_Flow_Growth], axis=1)
df
#The operational cashflow rate shows a decreasing trend for all three companies during the fiscal year 2022-23, with Microsoft reporting the least decrease of 2%.
#Although it also shows an increasing trend for all three companies during the fiscal year 2023-24, with Microsoft reporting the highest increase of 35%.

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow,Revenue Growth (%),Net Income Growth (%),Total Assets Growth (%),Total Liabilities Growth (%),Cash Flow Growth (%)
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000,NaN,NaN,NaN,NaN,NaN
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000,-3,-3,-0,-4,-10
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000,2,-3,4,6,7
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000,NaN,NaN,NaN,NaN,NaN
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000,7,-1,13,4,-2
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000,16,22,24,18,35
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000,NaN,NaN,NaN,NaN,NaN
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000,19,19,29,18,-10
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000,1,-52,14,13,13

In [22]:
#Adding a new feature 'Profit Margin'
def calculate_profit_margin(row):
  net_income = row['Net Income']
  total_revenue = row['Total Revenue']
  Profit_Margin = (net_income / total_revenue) * 100
  return Profit_Margin
df['Profit_Margin'] = df.apply(calculate_profit_margin, axis=1)
df

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow,Revenue Growth (%),Net Income Growth (%),Total Assets Growth (%),Total Liabilities Growth (%),Cash Flow Growth (%),Profit_Margin
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000,NaN,NaN,NaN,NaN,NaN,25
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000,-3,-3,-0,-4,-10,25
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000,2,-3,4,6,7,24
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000,NaN,NaN,NaN,NaN,NaN,37
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000,7,-1,13,4,-2,34
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000,16,22,24,18,35,36
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000,NaN,NaN,NaN,NaN,NaN,15
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000,19,19,29,18,-10,15
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000,1,-52,14,13,13,7

In [26]:
#Adding a new feature 'Return on Equity(ROE)'
def calculate_roe(row):
  net_income = row['Net Income']
  equity = row['Total Assets'] - row['Total Liabilities']
  ROE = (net_income / equity) * 100
  return ROE
df['ROE'] = df.apply(calculate_roe, axis=1)
df

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow,Revenue Growth (%),Net Income Growth (%),Total Assets Growth (%),Total Liabilities Growth (%),Cash Flow Growth (%),Profit_Margin,ROE
8,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000,NaN,NaN,NaN,NaN,NaN,25,197
7,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000,-3,-3,-0,-4,-10,25,156
6,Apple,2024,391035000000,93736000000,364980000000,308030000000,118254000000,2,-3,4,6,7,24,165
2,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000,NaN,NaN,NaN,NaN,NaN,37,44
1,Microsoft,2023,211915000000,72316000000,411976000000,205753000000,87582000000,7,-1,13,4,-2,34,35
0,Microsoft,2024,245122000000,88136000000,512163000000,243686000000,118548000000,16,22,24,18,35,36,33
5,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000,NaN,NaN,NaN,NaN,NaN,15,27
4,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000,19,19,29,18,-10,15,24
3,Tesla,2024,97690000000,7153000000,122070000000,48390000000,14923000000,1,-52,14,13,13,7,10